// 101 Good Practices
// Source: 101 Good Practices.md

export const practices = [
  "Do your work—do it on time and fully, if not early and overabundantly.",
  "Deal plainly.",
  "Acknowledge failure.",
  "There exists uncanny congruity between thought and experience.",
  "Pay people on time.",
  "Be willing to clean toilets and wash floors.",
  "Do not over-talk.",
  "Speak only of what you know well.",
  "Apologize.",
  "Judge quality not category.",
  "Research every important question independently.",
  "Expect corruption.",
  "\"Beware the devastation of conflict; war must never be pursued lightly.\" (Sun Tzu)",
  "The loftier the language, the lower the behavior.",
  "Take due credit. You will get blame when you do not deserve it.",
  "Do not complain.",
  "Thank people sincerely.",
  "Argue with a fool, make a fool your colleague.",
  "Measure twice.",
  "Get away from cruel people—at all costs.",
  "People lie.",
  "Great execution matters far more than great ideas.",
  "Never humor or accommodate bullies.",
  "Humiliate no one.",
  "People see only those traits they possess.",
  "Focus on one area of expertise and know it comprehensively.",
  "Relationships define your life and happiness.",
  "Never underestimate money or sex.",
  "Far better to find your group than to win people over.",
  "\"The art of war is the art of deception.\" (Sun Tzu)",
  "In terms of investments, virtually nothing, over time, outpaces an index fund.",
  "Brilliant people are wrong all the time.",
  "When you feel a sense of unease, honor it without question.",
  "The only real emergency is a medical emergency.",
  "Give no second chances to anyone who shows disrespect.",
  "\"In the long run, we find what we expect. We shall be fortunate then if we expect great things.\" (Thoreau)",
  "Honor every religion.",
  "Look people in the eye, recognize them, acknowledge them.",
  "Tip well.",
  "Eschew rhetorical questions.",
  "Use sarcasm rarely.",
  "Do not be an asshole.",
  "Learn to fight.",
  "Reduce food intake by twenty percent.",
  "Better to be nobly alone than settle for low company.",
  "Write nothing you would not want read aloud in public.",
  "You do not know someone until witnessing him in crisis.",
  "If you see someone mistreat another, he will mistreat you.",
  "No one cares about your political opinions; they care only whether you agree with theirs.",
  "Anger solves nothing.",
  "\"Who is evil? He who borrows and does not repay.\" (Ethics of the Fathers, Talmud)",
  "Unflinching perseverance is your single best chance of deliverance. Consider this lawful.",
  "Act decisively.",
  "Keep your hallowed wishes private.",
  "Be willing to pay qualified people for sound information or services.",
  "Beware those who keep pets that bite (including people).",
  "Respect workers.",
  "\"If we must choose between them, it is far safer to be feared than loved.\" (Machiavelli)",
  "There is no such thing as common sense.",
  "Emotions are far stronger than intellect.",
  "\"To work intelligently is education.\" (Elbert Hubbard)",
  "Cynics know nothing.",
  "Recheck your work—especially beginnings, endings, and the \"easy parts.\"",
  "Practice constantly.",
  "\"To feel brave, act as if we were brave.\" (William James)",
  "Nothing does more to squander goodwill than being a smartass.",
  "Concentration produces power.",
  "\"The past controls the future but the present controls the past.\" (G.I. Gurdjieff)",
  "Know your preferences, even if you cannot act on them.",
  "\"The way bread smells depends on how hungry a man is.\" (Arab proverb)",
  "Morality judges another; ethics judges self.",
  "A positive mental attitude means evaluating circumstances based on their capacity for self-development.",
  "\"A chief feature of false life is that it cannot stand alone, but frantically demands allies to support its false positions.\" (Vernon Howard)",
  "War or natural disaster abrogates nearly all of these rules; in such case health and survival are the laws.",
  "Eschew gossip, talebearing, and trash talk—especially for entertainment.",
  "Know who you are talking to.",
  "Do your absolute best to carry your own load before bothering another.",
  "\"Opposition is true Friendship\" (Blake)—but only if it is worthy opposition.",
  "Curiosity cannot be taught.",
  "\"Any reasonable order in an emergency is better than no order.\" (Major C.A. Bach)",
  "\"Be wise as serpents and harmless as doves.\" (Christ)",
  "We rarely work hard enough; cease only when you feel bodily fatigue.",
  "Boredom invites trouble.",
  "It is better and nobler to give away than lend money.",
  "Never give up hope that your tormenter will disappear or die. It happens constantly.",
  "Extra-physicality or spirituality is as real as the words you are now reading.",
  "There is no dishonor in electing to give in. Each conflict must end.",
  "\"He who proceeds violently across the earth will meet with a weary end. Know this and you know all my teachings.\" (Lao Tzu)",
  "Arrogance is stupidity.",
  "Never pick on people or make jokes at their expense; they have more problems than you know.",
  "\"What is fear of need but need itself?\" (Khalil Gibran)",
  "The only things you can really give another are money or time.",
  "\"Persistence amounting to madness should be avoided.\" (I Ching)",
  "Accept paradox.",
  "\"Chance favors the prepared mind.\" (Pasteur)",
  "Prepare for the day when your best friend betrays you.",
  "Keep your word.",
  "No one is as confident as someone who knows the least.",
  "Show respect.",
  "Those who bill by the hour work not for you but for the hour.",
  "\"The power of instruction is seldom of much efficacy, except in those happy dispositions where it is almost superfluous.\" (Edward Gibbon)"
];
